# Configuración local de Mosquitto — Actividad 3
# Este archivo NO tiene contraseñas ni datos sensibles, por eso se sube al repo.

listener 1883 0.0.0.0
allow_anonymous true

# Log básico para ver en consola qué se conecta y qué se publica
log_type error
log_type warning
log_type notice
log_type information

persistence false
